# Generated by Django 6.0 on 2025-12-25 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('job_role', models.CharField(blank=True, default='', max_length=200)),
                ('apply_route', models.CharField(blank=True, default='', max_length=200)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status_text', models.CharField(blank=True, default='', max_length=200)),
                ('memo', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ESVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateField(blank=True, null=True)),
                ('submitted_via', models.CharField(blank=True, default='', max_length=200)),
                ('result', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('PASS', 'Pass'), ('FAIL', 'Fail')], default='UNKNOWN', max_length=20)),
                ('memo', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='es_versions', to='core.company')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='es_versions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diff_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_email', models.CharField(blank=True, default='', max_length=254)),
                ('action', models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAIL', 'Login Fail'), ('LOGOUT', 'Logout'), ('COMPANY_CREATE', 'Company Create'), ('COMPANY_UPDATE', 'Company Update'), ('COMPANY_DELETE', 'Company Delete'), ('ES_CREATE', 'ES Create'), ('ES_UPDATE', 'ES Update'), ('ES_DELETE', 'ES Delete'), ('SETTINGS_UPDATE', 'Settings Update')], max_length=50)),
                ('target_type', models.CharField(blank=True, default='', max_length=50)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_auditl_user_id_969660_idx'), models.Index(fields=['action', '-created_at'], name='core_auditl_action_d80c2d_idx'), models.Index(fields=['-created_at'], name='core_auditl_created_1a76fa_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['owner', 'deadline'], name='core_compan_owner_i_e31d11_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['owner', '-updated_at'], name='core_compan_owner_i_4e4f8a_idx'),
        ),
        migrations.AddIndex(
            model_name='esversion',
            index=models.Index(fields=['owner', 'company'], name='core_esvers_owner_i_f472ea_idx'),
        ),
        migrations.AddIndex(
            model_name='esversion',
            index=models.Index(fields=['company', '-created_at'], name='core_esvers_company_5b3d8b_idx'),
        ),
    ]
