# Generated by Django 6.0 on 2025-12-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='esversion',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='es_files/'),
        ),
    ]
