# Generated by Django 6.0 on 2025-12-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_esversion_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='display_name',
            field=models.CharField(blank=True, default='就活 太郎', max_length=100),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='graduation_year',
            field=models.CharField(blank=True, default='2026年卒', max_length=20),
        ),
    ]
